# Generated by Django 3.0.8 on 2020-12-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='media')),
                ('description', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('shoe_size', models.IntegerField(verbose_name='Shoe Size')),
                ('gender', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('hasShoe', models.BooleanField()),
            ],
        ),
    ]
