# Generated by Django 3.0.8 on 2020-12-14 21:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_product_date_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.AlterField(
            model_name='product',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 21, 14, 55, 208774, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='hasShoe',
            field=models.BooleanField(default=True),
        ),
    ]
