# Generated by Django 3.1 on 2020-12-14 22:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201214_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 22, 59, 43, 914205, tzinfo=utc)),
        ),
    ]
