# Generated by Django 3.1 on 2020-12-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201217_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_submitted',
        ),
        migrations.RemoveField(
            model_name='product',
            name='email',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hasShoe',
        ),
        migrations.RemoveField(
            model_name='product',
            name='orderId',
        ),
        migrations.RemoveField(
            model_name='product',
            name='orderNumber',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shoe_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shoe_size',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
