# Generated by Django 3.1 on 2020-12-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201218_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shoe_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
