# Generated by Django 3.1 on 2020-12-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_product_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hasShoe',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
