# Generated by Django 3.1 on 2020-12-18 13:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_product_hasshoe'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 13, 3, 37, 908015, tzinfo=utc)),
        ),
    ]
