# Generated by Django 3.1 on 2020-12-18 13:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_product_date_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orderId',
            field=models.IntegerField(null=True, verbose_name='Order Id'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 13, 4, 24, 946109, tzinfo=utc)),
        ),
    ]
