# Generated by Django 3.1 on 2020-12-18 13:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20201218_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shoe_size',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 13, 22, 3, 162402, tzinfo=utc)),
        ),
    ]
