# Generated by Django 3.1 on 2020-12-18 13:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20201218_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orderNumber',
            field=models.IntegerField(null=True, verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 13, 23, 48, 835355, tzinfo=utc)),
        ),
    ]
