# Generated by Django 3.1 on 2020-12-19 23:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20201219_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default='shoe.jpg', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 19, 23, 49, 15, 731826, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='message',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
