# Generated by Django 3.1 on 2020-12-20 00:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20201219_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='started',
            new_name='accepted',
        ),
        migrations.AddField(
            model_name='product',
            name='denied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 0, 0, 15, 209574, tzinfo=utc)),
        ),
    ]
