# Generated by Django 3.0.8 on 2021-01-04 19:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20201220_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 19, 3, 20, 136577, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='hasShoe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='shoe_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
