# Generated by Django 3.0.8 on 2021-01-17 05:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20210117_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='archived',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 5, 45, 43, 752384, tzinfo=utc)),
        ),
    ]
