# Generated by Django 3.0.8 on 2021-01-17 19:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20210117_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=500)),
                ('rating', models.IntegerField(verbose_name='Rating')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 19, 2, 36, 177039, tzinfo=utc)),
        ),
    ]
