# Generated by Django 3.0.8 on 2021-01-17 20:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20210117_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 20, 3, 0, 279766, tzinfo=utc)),
        ),
    ]
