# Generated by Django 3.0.8 on 2021-01-18 22:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20210118_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='Rating'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 18, 22, 52, 45, 343946, tzinfo=utc)),
        ),
    ]
